# Generated by Django 3.2.7 on 2021-09-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_add_method_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=64)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flowcharts', to='chatbot.method')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
