# Generated by Django 3.2.7 on 2021-09-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_flowchart_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowchart',
            name='path',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
