# Generated by Django 3.2.7 on 2021-12-04 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_add_sampling_method_flowchart_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplingflowchart',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samplingflowcharts', to='chatbot.samplingmethod'),
        ),
    ]
