# Generated by Django 3.2.7 on 2021-12-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_sampling_project_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplingproject',
            name='path',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
